# Generated by Django 3.2.19 on 2023-06-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg', upload_to='images/'),
        ),
    ]
