# Generated by Django 3.2.19 on 2023-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../https://res.cloudinary.com/dobov5ccd/image/upload/v1686837368/media/images/river-rafting_ug2zbp.jpg', upload_to='images/'),
        ),
    ]
