# Generated by Django 3.2.19 on 2023-09-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230616_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../profile_image_o63wwb', upload_to='images/'),
        ),
    ]
